package com.kers.killove.jhsy.util

import android.content.Context
import com.kers.killove.jhsy.domain.AppSettings
import java.io.DataOutputStream
import java.io.File
import java.util.concurrent.TimeUnit

/**
 * 超级代理（仅本应用）：
 * - 需 Root 启动用户自定义代理内核（sing-box / Clash Meta / Xray 等）
 * - 内核只监听 127.0.0.1:本地端口，不开启 TUN / 透明代理 → 不影响其它 App
 * - 本应用通过 ProxyHttp 连接该本地端口即可
 *
 * 配置优先级：
 * 1. 用户填写的配置文件路径且文件存在 → 直接使用
 * 2. 否则若填写了订阅链接 → 自动生成默认 Clash Meta 配置（proxy-providers）
 * 3. 否则无法启动
 */
object SuperProxyController {

    const val DEFAULT_PORT = 17890

    data class Status(
        val hasRoot: Boolean,
        val enabled: Boolean,
        val running: Boolean,
        val binOk: Boolean,
        val configOk: Boolean,
        val localPort: Int,
        val pid: Int?,
        val message: String
    )

    data class ResolveResult(
        val configPath: String,
        val source: String, // "user" | "subscription" | "none"
        val message: String
    )

    fun workDir(context: Context): File =
        File(context.applicationContext.filesDir, "super_proxy").also { it.mkdirs() }

    fun pidFile(context: Context): File = File(workDir(context), "core.pid")
    fun logFile(context: Context): File = File(workDir(context), "core.log")
    fun autoConfigFile(context: Context): File = File(workDir(context), "auto_clash.yaml")

    fun status(context: Context, s: AppSettings): Status {
        val root = RootKeepAlive.hasRoot()
        val bin = s.superProxyBinPath.trim()
        val binOk = bin.isNotEmpty() && File(bin).exists()
        val port = s.superProxyLocalPort.coerceIn(1025, 65535)
        val resolved = resolveConfig(context, s)
        val configOk = resolved.source != "none" && File(resolved.configPath).exists()
        val pid = readPid(context)
        val running = pid != null && isPidAlive(pid)
        val msg = when {
            !s.superProxyEnabled -> "超级代理：未启用（仅本应用，需 Root + 内核）"
            !root -> "超级代理：无 Root，无法启动内核"
            !binOk -> "超级代理：请设置有效的内核路径"
            resolved.source == "none" -> "超级代理：请填订阅链接或自定义配置路径"
            running -> "超级代理：运行中 PID=$pid · 127.0.0.1:$port（${resolved.source}）"
            else -> "超级代理：已启用 · ${resolved.message} · 点击启动"
        }
        return Status(root, s.superProxyEnabled, running, binOk, configOk, port, pid, msg)
    }

    /**
     * 解析最终配置路径。
     * 优先级：用户自定义配置文件 > 订阅链接自动生成 Clash 默认配置。
     */
    fun resolveConfig(context: Context, s: AppSettings): ResolveResult {
        val userCfg = s.superProxyConfigPath.trim()
        if (userCfg.isNotEmpty() && File(userCfg).exists()) {
            return ResolveResult(userCfg, "user", "使用用户配置：$userCfg")
        }
        val sub = s.superProxySubUrl.trim()
        if (sub.isNotEmpty() && (sub.startsWith("http://") || sub.startsWith("https://"))) {
            val port = s.superProxyLocalPort.coerceIn(1025, 65535)
            val out = autoConfigFile(context)
            return try {
                writeClashSubscriptionConfig(out, sub, port)
                ResolveResult(
                    out.absolutePath,
                    "subscription",
                    "已由订阅生成默认 Clash 配置 → ${out.name}"
                )
            } catch (e: Exception) {
                ResolveResult("", "none", "生成默认配置失败：${e.message}")
            }
        }
        if (userCfg.isNotEmpty()) {
            return ResolveResult(
                userCfg,
                "none",
                "自定义配置不存在：$userCfg（可改填订阅链接自动生成）"
            )
        }
        return ResolveResult("", "none", "未设置配置：请填订阅链接或有效配置路径")
    }

    /**
     * 默认 Clash / Clash Meta 配置：
     * - mixed-port 绑定 127.0.0.1（HTTP+SOCKS，本应用连 SOCKS5）
     * - 无 TUN / 无透明代理
     * - proxy-providers 拉取订阅，自动节点
     */
    fun writeClashSubscriptionConfig(out: File, subscriptionUrl: String, localPort: Int) {
        val yaml = """
            # Auto-generated by wallpaper_app SuperProxy — do not edit while running
            # Priority: user config path overrides this file
            mixed-port: $localPort
            bind-address: 127.0.0.1
            allow-lan: false
            mode: rule
            log-level: warning
            ipv6: false
            external-controller: ""

            dns:
              enable: true
              enhanced-mode: fake-ip
              nameserver:
                - 1.1.1.1
                - 8.8.8.8

            proxy-providers:
              sub:
                type: http
                url: "${subscriptionUrl.replace("\"", "\\\"")}"
                interval: 3600
                path: ./provider_sub.yaml
                health-check:
                  enable: true
                  url: http://www.gstatic.com/generate_204
                  interval: 600

            proxies: []

            proxy-groups:
              - name: PROXY
                type: select
                use:
                  - sub
                proxies:
                  - DIRECT

            rules:
              - MATCH,PROXY
        """.trimIndent() + "\n"
        out.parentFile?.mkdirs()
        out.writeText(yaml)
    }

    fun readPid(context: Context): Int? = try {
        val f = pidFile(context)
        if (!f.exists()) null
        else f.readText().trim().toIntOrNull()
    } catch (_: Exception) {
        null
    }

    fun isPidAlive(pid: Int): Boolean {
        if (pid <= 0) return false
        return try {
            val p = Runtime.getRuntime().exec(arrayOf("sh", "-c", "kill -0 $pid 2>/dev/null"))
            val ok = p.waitFor(1, TimeUnit.SECONDS) && p.exitValue() == 0
            p.destroy()
            ok
        } catch (_: Exception) {
            try {
                val p = Runtime.getRuntime().exec("su")
                DataOutputStream(p.outputStream).use { os ->
                    os.writeBytes("kill -0 $pid 2>/dev/null\n")
                    os.writeBytes("exit\n")
                    os.flush()
                }
                p.waitFor(2, TimeUnit.SECONDS) && p.exitValue() == 0
            } catch (_: Exception) {
                false
            }
        }
    }

    /**
     * 启动内核。成功返回 null，失败返回错误文案。
     * 启动前自动 resolveConfig（用户配置优先，否则订阅生成默认配置）。
     */
    fun start(context: Context, s: AppSettings): String? {
        if (!RootKeepAlive.hasRoot()) return "无 Root 权限"
        val bin = s.superProxyBinPath.trim()
        if (bin.isEmpty() || !File(bin).exists()) return "内核文件不存在：$bin"

        val resolved = resolveConfig(context, s)
        if (resolved.source == "none" || resolved.configPath.isBlank()) {
            return resolved.message.ifBlank { "请填订阅链接或自定义配置路径" }
        }
        val cfg = resolved.configPath
        if (!File(cfg).exists()) return "配置文件不存在：$cfg"

        val port = s.superProxyLocalPort.coerceIn(1025, 65535)
        val wd = workDir(context).absolutePath
        val log = logFile(context).absolutePath
        val pidPath = pidFile(context).absolutePath

        stop(context)

        val argsTemplate = s.superProxyArgs.ifBlank { defaultArgsFor(bin) }
        val args = argsTemplate
            .replace("{bin}", shellQuote(bin))
            .replace("{config}", shellQuote(cfg))
            .replace("{port}", port.toString())
            .replace("{workdir}", shellQuote(wd))

        val runCmd = if (argsTemplate.contains("{bin}")) {
            args
        } else {
            "${shellQuote(bin)} $args"
        }

        // root 写 pid/log 后 chmod，避免 app 读不到；先清空旧日志
        val script = """
            chmod 755 ${shellQuote(bin)} 2>/dev/null
            mkdir -p ${shellQuote(wd)}
            cd ${shellQuote(wd)} || exit 1
            : > ${shellQuote(log)}
            chmod 666 ${shellQuote(log)} 2>/dev/null
            echo "CMD: $runCmd" >> ${shellQuote(log)}
            nohup $runCmd >>${shellQuote(log)} 2>&1 &
            echo ${'$'}! > ${shellQuote(pidPath)}
            chmod 666 ${shellQuote(pidPath)} 2>/dev/null
            chmod 666 ${shellQuote(log)} 2>/dev/null
        """.trimIndent()

        return try {
            val p = Runtime.getRuntime().exec("su")
            DataOutputStream(p.outputStream).use { os ->
                script.lines().forEach { line ->
                    os.writeBytes(line + "\n")
                }
                os.writeBytes("exit\n")
                os.flush()
            }
            val finished = p.waitFor(8, TimeUnit.SECONDS)
            if (!finished) {
                return "su 命令超时（请确认已授权 Root）"
            }
            // mihomo 拉订阅可能稍慢，多等一会儿再判定
            Thread.sleep(1200)
            val pid = readPid(context)
            if (pid != null && isPidAlive(pid)) null
            else {
                val tail = runCatching {
                    logFile(context).readText().takeLast(800)
                }.getOrDefault("(无日志，可能无 Root 权限或路径不可写)")
                "启动失败或进程已退出（配置来源=${resolved.source}，cfg=$cfg）。\n$tail"
            }
        } catch (e: Exception) {
            "启动异常：${e.message}"
        }
    }

    fun stop(context: Context): Boolean {
        val pid = readPid(context)
        if (!RootKeepAlive.hasRoot()) {
            if (pid != null) {
                try {
                    Runtime.getRuntime().exec(arrayOf("kill", "-9", pid.toString())).waitFor(1, TimeUnit.SECONDS)
                } catch (_: Exception) {
                }
            }
            runCatching { pidFile(context).delete() }
            return true
        }
        return try {
            val p = Runtime.getRuntime().exec("su")
            DataOutputStream(p.outputStream).use { os ->
                if (pid != null) {
                    os.writeBytes("kill $pid 2>/dev/null\n")
                    os.writeBytes("kill -9 $pid 2>/dev/null\n")
                }
                os.writeBytes("exit\n")
                os.flush()
            }
            p.waitFor(3, TimeUnit.SECONDS)
            runCatching { pidFile(context).delete() }
            true
        } catch (_: Exception) {
            false
        }
    }

    /** 根据二进制名猜默认参数 */
    fun defaultArgsFor(binPath: String): String {
        val name = File(binPath).name.lowercase()
        return when {
            name.contains("sing-box") || name == "singbox" ->
                "run -c {config}"
            name.contains("xray") ->
                "run -c {config}"
            name.contains("clash") ->
                "-f {config} -d {workdir}"
            name.contains("mihomo") ->
                "-f {config} -d {workdir}"
            name.contains("v2ray") ->
                "run -c {config}"
            else ->
                "-c {config}"
        }
    }

    private fun shellQuote(s: String): String =
        "'" + s.replace("'", "'\\''") + "'"
}
